import { SVGProps } from "react";
import {
	DarkIcon,
	BugIcon,
	DragonIcon,
	ElectricIcon,
	FairyIcon,
	FightingIcon,
	FireIcon,
	FlyingIcon,
	GhostIcon,
	GrassIcon,
	GroundIcon,
	IceIcon,
	NormalIcon,
	PoisonIcon,
	PsychicIcon,
	RockIcon,
	SteelIcon,
	WaterIcon,
} from "../components/typesIcons";
import { TypesPokemonType } from "@/types/typesPokemon";
export const TYPE_ICONS: Record<TypesPokemonType, React.FC<SVGProps<SVGSVGElement>>> = {
	normal: NormalIcon,
	fire: FireIcon,
	water: WaterIcon,
	electric: ElectricIcon,
	grass: GrassIcon,
	ice: IceIcon,
	fighting: FightingIcon,
	poison: PoisonIcon,
	ground: GroundIcon,
	flying: FlyingIcon,
	psychic: PsychicIcon,
	bug: BugIcon,
	rock: RockIcon,
	ghost: GhostIcon,
	dragon: DragonIcon,
	dark: DarkIcon,
	steel: SteelIcon,
	fairy: FairyIcon,
} as const;
export const TYPE_COLORS: Record<TypesPokemonType, string> = {
	normal: "#A8A878",
	fire: "#F08030",
	water: "#6890F0",
	electric: "#F8D030",
	grass: "#78C850",
	ice: "#98D8D8",
	fighting: "#C03028",
	poison: "#A040A0",
	ground: "#E0C068",
	flying: "#A890F0",
	psychic: "#F85888",
	bug: "#A8B820",
	rock: "#B8A038",
	ghost: "#705898",
	dragon: "#7038F8",
	dark: "#705848",
	steel: "#B8B8D0",
	fairy: "#EE99AC",
} as const;
